Ensure workflow delete resources
WASdev/azure.websphere-traditional.image pull request #105
Opened 2024-02-23 01:29 UTC by backwind1233

2024-02-23 08:30 UTC, backwind1233 commented
@majguo , please help to review this PR.

2024-02-26 08:42 UTC, majguo approved these changes
LGTM

2024-02-27 01:52 UTC, edburns requested changes
The optionality of the image number needs to be updated in the documentation for IBM:

https://github.com/WASdev/azure.websphere-traditional.image/blob/main/docs/howto-update-image.md

Please also make the necessary changes in this file.

Read https://github.com/WASdev/azure.websphere-traditional.image/blob/main/docs/howto-cleanup-after-image-published.md and make sure none of the changes in this PR impact the steps in this file.

Finally, I'm going to ask for Jianguo to also review this.

2024-03-04 21:53 UTC, edburns approved these changes

2024-03-06 16:44 UTC, venunathb approved these changes

2024-03-06 16:44 UTC, merged